export const DIVISIONES_CATALOGO = [
  "Electronica / Linea Blanca",
  "Hogar",
  "Ferreteria",
  "Pinturas",
  "Banos y griferia",
  "Decoracion",
  "Herramientas",
  "Materiales de construccion",
  "Iluminacion",
  "Jardin",
  "Automotriz",
  "Plomeria",
  "Electricidad",
  "Pisos y revestimientos",
  "Muebles",
  "Temporada",
];

export const catalogosIniciales = [
  {
    id: "cat-001",
    nombre: "Bifoliar Junio 2026",
    canal: "Retail",
    vigencia_inicio: "2026-06-01",
    vigencia_fin: "2026-06-30",
    vigencia: "01 Jun - 30 Jun",
    estado: "Activo",
    color: "bg-emerald-700",
    docId: "local-bifoliar-junio2026",
    tokenConexion: "********",
    notificaciones: true,
    correos: "mercadeo@sinsa.com.ni; pricing@sinsa.com.ni; planimetria@sinsa.com.ni",
  },
  {
    id: "cat-002",
    nombre: "Catálogo Galerón Junio",
    canal: "Galerón",
    vigencia_inicio: "2026-06-05",
    vigencia_fin: "2026-06-25",
    vigencia: "05 Jun - 25 Jun",
    estado: "Borrador",
    color: "bg-sky-600",
    docId: "local-galeron-junio2026",
    tokenConexion: "********",
    notificaciones: false,
    correos: "pricing@sinsa.com.ni",
  },
  {
    id: "cat-003",
    nombre: "Comasa Especial",
    canal: "Comasa",
    vigencia_inicio: "2026-06-10",
    vigencia_fin: "2026-06-20",
    vigencia: "10 Jun - 20 Jun",
    estado: "Activo",
    color: "bg-yellow-500",
    docId: "local-comasa-junio2026",
    tokenConexion: "********",
    notificaciones: true,
    correos: "mercadeo@sinsa.com.ni; operaciones@sinsa.com.ni",
  },
];

export const compradoresIniciales = [
  { nombre: "Marcela Torrez", comprador: "Marcela Torrez", division: "Electrónica / Línea Blanca", correo: "", activo: true },
  { nombre: "Rosa Rodriguez", comprador: "Rosa Rodriguez", division: "Hogar", correo: "", activo: true },
  { nombre: "Octavio Palacios", comprador: "Octavio Palacios", division: "Ferretería", correo: "", activo: true },
  { nombre: "Mariela Espinoza", comprador: "Mariela Espinoza", division: "Pinturas", correo: "", activo: true },
  { nombre: "Cynthia Fitoria", comprador: "Cynthia Fitoria", division: "Baños y grifería", correo: "", activo: true },
  { nombre: "Hazel Cruz", comprador: "Hazel Cruz", division: "Decoración", correo: "", activo: true },
  { nombre: "Jose Maria", comprador: "Jose Maria", division: "Herramientas", correo: "", activo: true },
];

export const responsablesSolicitudesIniciales = [
  { responsable_id: "resp-pricing", nombre: "Equipo Pricing", area: "Pricing", correo: "", activo: true },
  { responsable_id: "resp-mercadeo", nombre: "Equipo Mercadeo", area: "Mercadeo", correo: "", activo: true },
  { responsable_id: "resp-planimetria", nombre: "Equipo Planimetria", area: "Planimetria", correo: "", activo: true },
];

export const segmentosClientesIniciales = [
  { segmento_id: "1002", nombre_segmento: "Managua", segmento: "Managua", canal: "comasa", activo: true, orden: 1 },
  { segmento_id: "1003", nombre_segmento: "Foraneo", segmento: "Foraneo", canal: "comasa", activo: true, orden: 2 },
  { segmento_id: "1102", nombre_segmento: "Managua 1", segmento: "Managua 1", canal: "comasa", activo: true, orden: 3 },
  { segmento_id: "1103", nombre_segmento: "Managua2", segmento: "Managua2", canal: "comasa", activo: true, orden: 4 },
  { segmento_id: "1104", nombre_segmento: "Foraneo 1", segmento: "Foraneo 1", canal: "comasa", activo: true, orden: 5 },
  { segmento_id: "1105", nombre_segmento: "Foraneo 2", segmento: "Foraneo 2", canal: "comasa", activo: true, orden: 6 },
  { segmento_id: "1007", nombre_segmento: "Gold", segmento: "Gold", canal: "retail", activo: true, orden: 1 },
  { segmento_id: "1001", nombre_segmento: "Bronce", segmento: "Bronce", canal: "retail", activo: true, orden: 2 },
  { segmento_id: "1005", nombre_segmento: "Platinium", segmento: "Platinium", canal: "retail", activo: true, orden: 3 },
];

export const rowsIniciales = [
  {
    id: "r1",
    row_id: "r1",
    tipoPromo: "Descuento",
    tipo_promo: "Descuento",
    actividad_id: "BIFOLIAR_JUN2026",
    oferta_id: "OFE-BIFOLIAR_JUN2026-DESCUENTO-r1",
    grupoOferta: "Descuento",
    grupo_oferta: "Descuento",
    tipoSku: "simple",
    tipo_sku: "simple",
    sku: "200001",
    numParte: "PINT-BLA-GL",
    num_parte: "PINT-BLA-GL",
    descripcion: "Pintura látex blanca galón",
    tipoCantidad: "Exacta",
    tipo_cantidad: "Exacta",
    cantidadMinima: 1,
    cantidad_minima: 1,
    precioAntes: 18.5,
    precio_antes: 18.5,
    precioAhora: 15.99,
    precio_ahora: 15.99,
    descuento: "14%",
    comentario: "Producto destacado en página interior",
    comentario_comprador: "Producto destacado en página interior",
    comprador: "Marcela Torrez",
    division: "Pinturas",
    estado_registro: "BORRADOR",
  },
  {
    id: "r2",
    row_id: "r2",
    tipoPromo: "Combo",
    tipo_promo: "Combo",
    actividad_id: "BIFOLIAR_JUN2026",
    oferta_id: "OFE-BIFOLIAR_JUN2026-COMBO-combo-1",
    grupoOferta: "combo-1",
    grupo_oferta: "combo-1",
    tipoSku: "principal",
    tipo_sku: "principal",
    sku: "100001",
    numParte: "TV-55-QLED",
    num_parte: "TV-55-QLED",
    descripcion: "Televisor Smart QLED 55 pulgadas 4K",
    tipoCantidad: "Exacta",
    tipo_cantidad: "Exacta",
    cantidadMinima: 1,
    cantidad_minima: 1,
    precioAntes: 499.99,
    precio_antes: 499.99,
    precioAhora: 399.99,
    precio_ahora: 399.99,
    descuento: "20%",
    comentario: "Principal de combo",
    comentario_comprador: "Principal de combo",
    comprador: "Marcela Torrez",
    division: "Electrónica / Línea Blanca",
    estado_registro: "BORRADOR",
  },
  {
    id: "r3",
    row_id: "r3",
    tipoPromo: "Combo",
    tipo_promo: "Combo",
    actividad_id: "BIFOLIAR_JUN2026",
    oferta_id: "OFE-BIFOLIAR_JUN2026-COMBO-combo-1",
    grupoOferta: "combo-1",
    grupo_oferta: "combo-1",
    tipoSku: "recompensa",
    tipo_sku: "recompensa",
    sku: "100002",
    numParte: "SB-200",
    num_parte: "SB-200",
    descripcion: "Barra de sonido Bluetooth 200W",
    tipoCantidad: "Exacta",
    tipo_cantidad: "Exacta",
    cantidadMinima: 1,
    cantidad_minima: 1,
    precioAntes: 129.99,
    precio_antes: 129.99,
    precioAhora: 0,
    precio_ahora: 0,
    descuento: "100%",
    comentario: "Regalía",
    comentario_comprador: "Regalía",
    comprador: "Marcela Torrez",
    division: "Electrónica / Línea Blanca",
    estado_registro: "BORRADOR",
  },
];

export const comentariosIniciales = [
  {
    id: "c1",
    comentario_id: "c1",
    actividadId: "BIFOLIAR_JUN2026",
    actividad_id: "BIFOLIAR_JUN2026",
    rowId: "r2",
    row_id: "r2",
    alcanceComentario: "LINEA",
    alcance_comentario: "LINEA",
    usuario: "Diseño Mercadeo",
    tipo_usuario: "Mercadeo",
    texto: "Confirmar si la barra de sonido debe mostrarse como regalía visible en el arte.",
    comentario: "Confirmar si la barra de sonido debe mostrarse como regalía visible en el arte.",
    estado: "Abierto",
    fecha: "28/05/2026, 09:10",
    prioridad: "MEDIA",
  },
];
