export const SHEETS = {
  CONFIG: "CONFIG",
  CATALOGOS: "CATALOGOS",
  ACTIVIDADES: "ACTIVIDADES",
  SEGMENTOS_CLIENTES: "segmentos_clientes",
  COMPRADORES: "COMPRADORES",
  RESPONSABLES_SOLICITUDES: "RESPONSABLES_SOLICITUDES",
  JERARQUIA_CATEGORIAS: "JERARQUIA_CATEGORIAS",
  PROMOCIONES: "PROMOCIONES",
  PROMOCIONES_DETALLE: "PROMOCIONES_DETALLE",
  AVANCES_CATALOGO: "AVANCES_CATALOGO",
  COMENTARIOS: "COMENTARIOS",
  LOGS: "LOGS",
  NOTIFICACIONES: "NOTIFICACIONES",
  CONSOLIDADO: "CONSOLIDADO",
  EXPORT_PRICING: "EXPORT_PRICING",
  EXPORT_MERCADEO: "EXPORT_MERCADEO",
  EXPORT_PLANIMETRIA: "EXPORT_PLANIMETRIA",
};

export const REQUIRED_SHEETS = [SHEETS.CONFIG, SHEETS.COMPRADORES, SHEETS.PROMOCIONES, SHEETS.COMENTARIOS, SHEETS.LOGS, SHEETS.NOTIFICACIONES];
